name: dlna
description: A simple DLNA DMC library implemented by Dart. It is tiny and only the basic network video casting function is supported.
homepage: https://github.com/succlz123/DLNA-Dart
version: 0.0.5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.6
  xml2json: ^5.3.1
  shared_preferences: ^2.0.6
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
